name: learn context varibales

on: 
  workflow_dispatch:

env:
  cloud: google-cloud

jobs:
  test_context_variables:
    runs-on: ubuntu-latest
    steps: 
    - name: "checking context variables"
      run: |
        echo "Repository name: ${{github.repository}}"
        echo "Workflow name: ${{github.workflow}}"
        echo "Triggered by : ${{github.triggering_actor}}"
        
